version: "3.8"

services:
  nginx:
    image: nginx:1.19.10-alpine
    ports:
      - 9000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - external-storage:/media/uploads

volumes:
  external-storage:
    external: true
